variables:
  RUST_VERSION: "1.95-alpine3.23"
  DOCKER_VERSION: "29.4.3"
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always


cache:
  key:
    files:
      - Cargo.lock
      - Cargo.toml
  paths:
    - target
    - .cargo/registry
    - .cargo/git

include:
  - local: ".gitlab/ci/code-quality.yml"
  - local: ".gitlab/ci/docker-build.yml"
  - local: ".gitlab/ci/etl-pipeline.yml"
  - local: ".gitlab/ci/weekly-report.yml"

stages:
  - quality
  - build
  - run-etl-pipeline
  - run-weekly-report
