image: rust:$RUST_VERSION

variables:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

stages:
  - quality

lint:
  stage: quality
  script:
    - rustup component add clippy rustfmt
    - cargo fmt --all -- --check
    - cargo clippy --workspace --all-targets --locked -- -D warnings
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.rs"
        - "**/Cargo.toml"
        - "**/Cargo.lock"
    - if: $CI_MERGE_REQUEST_DRAFT == "false"

build:
  stage: quality
  script:
    - cargo fetch
    - cargo check --workspace --all-targets --locked
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.rs"
        - "**/Cargo.toml"
        - "**/Cargo.lock"
    - if: $CI_MERGE_REQUEST_DRAFT == "false"
